# Generated by Django 5.2.6 on 2026-03-07 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0003_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCardConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(max_length=255)),
                ('resolucion', models.CharField(blank=True, max_length=255)),
                ('titulo_boletin', models.CharField(default='Boletín de calificaciones', max_length=255)),
                ('anio_lectivo', models.CharField(blank=True, max_length=20)),
                ('rector_nombre', models.CharField(blank=True, max_length=255)),
                ('director_grupo_nombre', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración de boletín',
                'verbose_name_plural': 'Configuración de boletín',
            },
        ),
        migrations.CreateModel(
            name='SubjectIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')])),
                ('descripcion', models.TextField()),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_boletin', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Indicador de materia',
                'verbose_name_plural': 'Indicadores de materias',
                'ordering': ['materia__nombre', 'periodo'],
                'unique_together': {('materia', 'periodo')},
            },
        ),
    ]
