# Generated by Django 5.2.6 on 2026-03-11 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_subject_options_subject_area'),
        ('report_cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(unique=True)),
            ],
            options={
                'verbose_name': 'Indicador',
                'verbose_name_plural': 'Indicadores',
                'ordering': ['descripcion'],
            },
        ),
        migrations.CreateModel(
            name='SubjectIndicatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.PositiveSmallIntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')])),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='report_cards.indicator')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores_asignados', to='courses.subject')),
            ],
            options={
                'verbose_name': 'Asignación de indicador',
                'verbose_name_plural': 'Asignaciones de indicadores',
                'ordering': ['materia__nombre', 'periodo', 'indicador__descripcion'],
                'unique_together': {('materia', 'periodo', 'indicador')},
            },
        ),
        migrations.DeleteModel(
            name='SubjectIndicator',
        ),
    ]
