# Generated by Django 5.2.6 on 2026-03-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report_cards', '0002_indicator_subjectindicatorassignment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcardconfig',
            name='periodo_actual',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
