# Generated by Django 5.2.6 on 2026-03-16 16:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_alter_subject_options_subject_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveSmallIntegerField()),
                ('alert_type', models.CharField(choices=[('LOW_GRADE', 'Bajo rendimiento'), ('ABSENCE_RISK', 'Riesgo por inasistencia'), ('MISSING_ASSIGNMENTS', 'Incumplimiento de tareas')], max_length=30)),
                ('level', models.CharField(choices=[('WARNING', 'Advertencia'), ('CRITICAL', 'Crítica')], default='WARNING', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Activa'), ('RESOLVED', 'Resuelta')], default='ACTIVE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message_student', models.TextField()),
                ('message_teacher', models.TextField()),
                ('message_admin', models.TextField()),
                ('metric_value', models.FloatField(blank=True, null=True)),
                ('threshold_value', models.FloatField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_alerts', to='courses.course')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_academic_alerts', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='academic_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta académica',
                'verbose_name_plural': 'Alertas académicas',
                'ordering': ['-created_at'],
                'unique_together': {('student', 'course', 'period', 'alert_type')},
            },
        ),
    ]
