# Generated by Django 5.2.6 on 2026-02-23 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_adminprofile_studentprofile_teacherprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_account',
            field=models.BooleanField(default=False),
        ),
    ]
