# Generated by Django 5.2.6 on 2026-09-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_user_signature_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='acudiente2_cedula',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='acudiente2_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='acudiente2_nombre',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='acudiente2_parentesco',
            field=models.CharField(blank=True, choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('CONOCIDO', 'Conocido')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='acudiente2_telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='acudiente_parentesco',
            field=models.CharField(blank=True, choices=[('MADRE', 'Madre'), ('PADRE', 'Padre'), ('TIO', 'Tío'), ('TIA', 'Tía'), ('ABUELO', 'Abuelo'), ('ABUELA', 'Abuela'), ('HERMANO', 'Hermano'), ('HERMANA', 'Hermana'), ('CONOCIDO', 'Conocido')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='telefono',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
