# Generated by Django 5.2.6 on 2026-02-26 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='nombre',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
