# Generated by Django 5.2.6 on 2026-02-27 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_alter_submission_calificacion'),
        ('courses', '0003_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='courses.subject'),
        ),
    ]
