# Generated by Django 5.2.6 on 2026-02-27 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_assignment_materia'),
        ('courses', '0003_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='courses.subject'),
        ),
    ]
