# Generated by Django 5.2.6 on 2026-02-27 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_alter_assignment_materia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='curso',
        ),
    ]
