# Generated by Django 5.2.6 on 2026-03-07 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_remove_assignment_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='periodo',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Periodo 1'), (2, 'Periodo 2'), (3, 'Periodo 3'), (4, 'Periodo 4')], default=1),
        ),
    ]
